In [1]:
import pandas as pd

In [2]:
import sys
import os

# Add project root (two levels up from notebooks/eda)
project_root = os.path.abspath(os.path.join(os.getcwd(), "../.."))
sys.path.append(project_root)

from src.api.NOAA_atmos_co2 import atmospheric_co2

In [5]:
atmos_co2 , update_date = atmospheric_co2()
# atmos_co2_df.tail()

update_date

'# File Creation: Wed Aug  5 10:21:49 2026'

In [6]:
# saving raw data 

atmos_co2.to_csv('../../data/raw/tmospheric_co2.csv')
atmos_co2.head()

   year  month  decimal date  average  deseasonalized  ndays  sdev   unc
0  1958      3     1958.2027   315.71          314.44     -1 -9.99 -0.99
1  1958      4     1958.2877   317.45          315.16     -1 -9.99 -0.99
2  1958      5     1958.3699   317.51          314.69     -1 -9.99 -0.99
3  1958      6     1958.4548   317.27          315.15     -1 -9.99 -0.99
4  1958      7     1958.5370   315.87          315.20     -1 -9.99 -0.99

In [12]:
atmos_co2.info()

<class 'pandas.DataFrame'>
RangeIndex: 821 entries, 0 to 820
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   year            821 non-null    int64
 1   month           821 non-null    int64
 2   decimal date    821 non-null    float64
 3   average         821 non-null    float64
 4   deseasonalized  821 non-null    float64
 5   ndays           821 non-null    int64
 6   sdev            821 non-null    float64
 7   unc             821 non-null    float64
dtypes: float64(5), int64(3)
memory usage: 51.4 KB

In [13]:
atmos_co2.describe( )

,year,month,decimal date,average,deseasonalized,ndays,sdev,unc
count,821.000000,821.000000,821.000000,821.000000,821.000000,821.000000,821.000000,821.000000
mean,1991.875761,6.490865,1992.374402,361.279805,361.266090,19.165652,-1.997600,-0.085286
std,19.764940,3.447371,19.763011,33.396504,33.323235,11.823987,4.481918,0.508555
min,1958.000000,1.000000,1958.202700,312.420000,314.440000,-1.000000,-9.990000,-0.990000
25%,1975.000000,4.000000,1975.291700,331.280000,330.850000,14.000000,0.210000,0.080000
50%,1992.000000,6.000000,1992.375000,356.340000,356.480000,25.000000,0.400000,0.150000
75%,2009.000000,9.000000,2009.458300,387.630000,387.540000,28.000000,0.570000,0.220000
max,2026.000000,12.000000,2026.541700,432.340000,429.050000,31.000000,1.310000,0.580000

In [10]:
atmos_co2.year.max()

np.int64(2026)